# Generated by Django 3.2.23 on 2024-05-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padi',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='padi',
            order_with_respect_to='user',
        ),
    ]
