# Generated by Django 3.2.23 on 2024-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='kategori',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
